name: .NET Core Linux Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build debug with dotnet
      run: dotnet build
    - name: Test debug with dotnet
      run: dotnet test
    - name: Pack debug with dotnet
      run: dotnet pack
    - name: Build release with dotnet
      run: dotnet build --configuration Release
    - name: Test release with dotnet
      run: dotnet test --configuration Release
    - name: Pack release with dotnet
      run: dotnet pack --configuration Release
